-- AlterTable
ALTER TABLE "EventLocation" ALTER COLUMN "startedAt" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "endedAt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "PossibleDate" ALTER COLUMN "date" SET DATA TYPE TIMESTAMP(3);
